### PR TITLE
CH4 VNI cleaned up patches

### PR DESCRIPTION
**Pull request by hajimefu**
This is a cleaned up patches of the "ch4-vni" branch.
It's rebased onto the latest master, to adapt to the latest netmod API (pmodels/mpich#2611).

The biggest news in this PR are these two:
* Added the "CH4 configuration set" idea, which is essentially a clone of OFI capability sets, to allow users to choose several configuration parameter either at compile time or runtime
* Added a configuration variable to choose whether to use per-object work queue or per-VNI work queue

If you are really curious about how things went, here are the history of change:
1. First Halim's `ch4-vni` branch was squashed and rebased onto the latest master:  https://github.com/hajimefu/mpich/commits/ch4-vni-halim-981a2c541-squashed
2. Then the squashed part was split into a few commits:  https://github.com/hajimefu/mpich/commits/ch4-vni-halim-981a2c541-reformatted
3. After that, my patches came in: https://github.com/hajimefu/mpich/commits/ch4-vni-hajimefu-c7e7f6f-reformatted
4. Reordered and squashed patches, so that CH4 configuration sets comes first

@halimamer please take a look.

### CODE REVIEW

**Comment by halimamer** [comment]
I think the ch4 capability set stuff is orthogonal to the vni stuff. What was the resolution on this idea?

**Comment by hajimefu** [comment]
We discussed it on the CH4 call and concluded that we wouldn't pursue CH4 configuration sets for now. Instead, we could use config.site file to make a group of several configuration parameters and have "runtime" configuration for each switch.
So I took out the CH4 configuration set part from this branch and updated it.

**Comment by hajimefu** [comment]
Rebased the branch on top of latest master as of today and updated for the upcoming hackathon.

**Comment by hajimefu** [comment]
Preceded by #3117

**Pull request closed without merging**
